import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

/**
 * POST /api/policies/summaries — precomputed plain-English summaries for the
 * statutory corpus cards, generated by `ml/summarize_corpus.py` (a local
 * distilbart model, no external API) and served from
 * `public/data/provision_summaries.json`. This endpoint only looks up ids.
 */

interface Item {
  id: string;
}

let cache: Record<string, string> | null = null;

function load(): Record<string, string> | null {
  if (cache) return cache;
  const path = join(process.cwd(), "public", "data", "provision_summaries.json");
  if (!existsSync(path)) return null;
  try {
    cache = JSON.parse(readFileSync(path, "utf8")) as Record<string, string>;
    return cache;
  } catch {
    return null;
  }
}

export async function handleSummariesApi(request: Request): Promise<Response> {
  const json = (data: unknown, status = 200) =>
    new Response(JSON.stringify(data), {
      status,
      headers: { "content-type": "application/json;charset=utf-8" },
    });

  if (request.method !== "POST") return json({ error: "POST only" }, 405);
  let body: { items?: Item[] };
  try {
    body = (await request.json()) as { items?: Item[] };
  } catch {
    return json({ error: "Invalid JSON" }, 400);
  }
  const items = (body.items ?? []).filter((i) => i && typeof i.id === "string");
  const map = load();
  if (!map) return json({ summaries: {}, model: null, configured: false });
  const summaries: Record<string, string> = {};
  for (const it of items) {
    const s = map[it.id];
    if (s) summaries[it.id] = s;
  }
  return json({ summaries, model: "sshleifer/distilbart-cnn-12-6 (local)" });
}
