/**
 * The layer manager's source of truth: every checkbox the 3D GIS Explorer can
 * show, its render path, its legend and — most importantly — its provenance.
 *
 * `status` is not decoration:
 *   "connected"  real, wired data source rendered on the globe
 *   "demo"       rendered, but from in-repo demo/modelled aggregates — labelled
 *   "unavailable"no dataset is wired; the UI must say so instead of inventing
 *
 * Sources referenced here are the same ones already documented in
 * src/data/data-sources.ts and the README data-sources table.
 */
import type { GisLayerDef } from "./types";

const NOVEMBER_2024 = "2024-11-01";

const OSM_EVIDENCE = (coverage: string) => ({
  source: "OpenStreetMap",
  provider: "OpenStreetMap contributors",
  date: "rolling",
  resolution: "object level",
  coverage,
  license: "ODbL 1.0",
  processing: "Live Overpass query restricted to the current camera bounding box.",
  kind: "observed" as const,
  confidence: "Crowd-sourced ground survey; completeness varies by region.",
});

const stateIntelEvidence = (source: string, processing: string, field: string) => ({
  source,
  provider: "NIRVANA demo aggregates (src/data/state-intelligence.ts)",
  date: "2024",
  resolution: "State / UT",
  coverage: "National (35 states & UTs)",
  license: "Demo dataset — not an official statistic",
  processing,
  kind: "demo" as const,
  confidence: `DEMO value. ${field} is a placeholder aggregate until the national layer is wired; never quote as official.`,
});

const landMixEvidence = (processing: string) => ({
  source: "Land-mix shares per state (land-scenario model)",
  provider: "NIRVANA (src/data/land-scenario.ts)",
  date: "2018–2024 series",
  resolution: "State / UT",
  coverage: "National (35 states & UTs)",
  license: "Modelled output of NIRVANA land scenario model",
  processing,
  kind: "modelled" as const,
  confidence:
    "Modelled state-level composition. Not a parcel-level classification and not observed per-pixel land cover.",
});

const unavailable = (note: string): Pick<GisLayerDef, "status" | "unavailableNote" | "hint"> => ({
  status: "unavailable",
  unavailableNote: note,
  hint: "No licensed dataset wired into this route",
});

export const GIS_LAYERS: GisLayerDef[] = [
  /* ---------------------------------------------------------------- BASE -- */
  {
    id: "satellite",
    group: "base",
    label: "Satellite",
    hint: "Sentinel-2 cloudless mosaics, year-switchable",
    status: "connected",
    unavailableNote: null,
    render: "satellite-imagery",
    defaultOn: true,
    color: "#2f6fb5",
    legend: [],
    evidence: {
      source: "Sentinel-2 cloudless global mosaic",
      provider: "Copernicus Sentinel-2 · EOX IT Services",
      date: "Annual mosaics 2018–2024",
      resolution: "10 m bands, rendered as 256 px tiles",
      coverage: "Global",
      license: "Free for any use with attribution (EOX)",
      processing:
        "WMTS tiles `s2cloudless-{year}_3857` requested per view; the year follows the timeline slider.",
      kind: "observed",
      confidence: "Cloud-free composite of Copernicus Sentinel-2 observations.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "street",
    group: "base",
    label: "Street / basemap",
    hint: "OpenStreetMap tiles",
    status: "connected",
    unavailableNote: null,
    render: "street-imagery",
    defaultOn: false,
    color: "#8a8f98",
    legend: [],
    evidence: {
      ...OSM_EVIDENCE("Global"),
      processing: "Standard XYZ raster tiles from tile.openstreetmap.org.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "terrain",
    group: "base",
    label: "Terrain",
    hint: "Elevation relief when a terrain provider is reachable",
    status: "connected",
    unavailableNote: null,
    render: "terrain",
    defaultOn: true,
    color: "#8f6f3d",
    legend: [],
    evidence: {
      source: "Cesium World Terrain (ellipsoid fallback)",
      provider: "Cesium Ion · fallback: WGS84 ellipsoid",
      date: "n/a",
      resolution: "≈ 30 m posts when available",
      coverage: "Global",
      license: "Cesium Ion terms when available; ellipsoid is public WGS84",
      processing:
        "Terrain provider is probed at startup. If Ion cannot be reached the globe falls back to the WGS84 ellipsoid and the panel says so — elevation is then reported as unavailable rather than estimated.",
      kind: "observed",
      confidence:
        "Conditional: real relief only when the terrain provider connects. Status is shown live in the DATA INFO dialog.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "buildings",
    group: "base",
    label: "3D buildings",
    hint: "OSM building volumes extruded in Cesium",
    status: "connected",
    unavailableNote: null,
    render: "buildings",
    defaultOn: true,
    color: "#7a6f5f",
    legend: [{ label: "Extruded building footprint", color: "#cbbfa9" }],
    evidence: OSM_EVIDENCE(
      "Camera viewport only — India-wide coverage depends on OSM building tagging density.",
    ),
    statField: null,
    landClass: null,
  },
  {
    id: "roads",
    group: "base",
    label: "Roads",
    hint: "Highway centrelines in the viewport",
    status: "connected",
    unavailableNote: null,
    render: "overpass",
    defaultOn: false,
    color: "#b08a4a",
    legend: [],
    evidence: OSM_EVIDENCE("Camera viewport only"),
    statField: null,
    landClass: null,
  },
  {
    id: "water",
    group: "base",
    label: "Water",
    hint: "Rivers, lakes and reservoirs in the viewport",
    status: "connected",
    unavailableNote: null,
    render: "overpass",
    defaultOn: false,
    color: "#2878d0",
    legend: [{ label: "Open water", color: "#2878d0" }],
    evidence: OSM_EVIDENCE("Camera viewport only"),
    statField: null,
    landClass: null,
  },
  {
    id: "admin",
    group: "base",
    label: "Administrative boundaries",
    hint: "State & UT outlines, plus searched district/taluka rings",
    status: "connected",
    unavailableNote: null,
    render: "admin",
    defaultOn: true,
    color: "#4f7a4f",
    legend: [{ label: "State / UT boundary", color: "#5c7f5c" }],
    evidence: {
      source: "State boundaries GeoJSON (india-states.json) + Nominatim polygons",
      provider: "In-repo extract · OpenStreetMap / Nominatim for drill-down rings",
      date: "Extract vintage 2015 (simplified 2024)",
      resolution: "State / UT level; district & below from live geocoding",
      coverage: "National — 35 states & union territories",
      license: "Open community maps",
      processing:
        "State rings are draped as polylines. District/taluka rings are fetched on demand with Nominatim `polygon_geojson=1`, bounded to the searched place — never a nationwide file.",
      kind: "observed",
      confidence: "Generalised boundaries. Not a legal cadastral or demarcation line.",
    },
    statField: null,
    landClass: null,
  },

  /* ---------------------------------------------------------------- LAND -- */
  {
    id: "parcels",
    group: "land",
    label: "Cadastral parcels",
    hint: "Survey parcels where a public release is wired",
    status: "connected",
    unavailableNote: null,
    render: "parcels",
    defaultOn: true,
    color: "#0d7a4f",
    legend: [
      { label: "Cadastral parcel", color: "#0d7a4f" },
      { label: "Selected", color: "#004e2b" },
    ],
    evidence: {
      source: "Imported cadastral releases via GET /api/parcels?bbox=",
      provider: "indianopenmaps.com (Datameet) · MRSAC / state revenue releases",
      date: "Per-release; not stated upstream for some releases",
      resolution: "Individual survey-parcel polygons",
      coverage:
        "PARTIAL — parcel-level data is available for wired demonstration areas only (e.g. Vadnerbhairav, Chandwad). Not nationwide.",
      license: "CC0 (Datameet aggregation; attribution requested to Datameet + MRSAC)",
      processing:
        "Server pre-filters an in-repo parcel store by bounding box; the response is draped as translucent polygons. Outside wired areas the panel reads “Parcel-level data unavailable for this location.”",
      kind: "observed",
      confidence:
        "Real geometry where the release exists. Attributes carry village/taluka/district codes; survey number is reported only when the source actually carries it.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "lulc",
    group: "land",
    label: "Land use",
    hint: "State-level composition from the land-scenario model",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#c8a415",
    legend: [
      { label: "Agriculture", color: "#F6C515" },
      { label: "Forest", color: "#249B45" },
      { label: "Built-up", color: "#E53935" },
      { label: "Water", color: "#2878D0" },
      { label: "Barren / other", color: "#C8B58A" },
    ],
    evidence: landMixEvidence(
      "State land-mix shares are painted onto each state outline. This is a modelled state aggregate, not a pixel classification of the satellite imagery.",
    ),
    statField: null,
    landClass: null,
  },
  {
    id: "agri",
    group: "land",
    label: "Agriculture",
    hint: "Agricultural share of land mix, per state",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#F6C515",
    legend: [
      { label: "Lower share", color: "#f7e6a6" },
      { label: "Higher share", color: "#F6C515" },
    ],
    evidence: landMixEvidence(
      "Ramp = agricultural share of each state's modelled land mix for the timeline year.",
    ),
    statField: null,
    landClass: "agri",
  },
  {
    id: "forest",
    group: "land",
    label: "Forest",
    hint: "Forest share of land mix, per state",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#249B45",
    legend: [
      { label: "Lower share", color: "#d6ebd9" },
      { label: "Higher share", color: "#249B45" },
    ],
    evidence: landMixEvidence(
      "Ramp = forest share of each state's modelled land mix for the timeline year.",
    ),
    statField: null,
    landClass: "forest",
  },
  {
    id: "built",
    group: "land",
    label: "Built-up",
    hint: "Built-up share of land mix, per state",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#E53935",
    legend: [
      { label: "Lower share", color: "#f6cfcb" },
      { label: "Higher share", color: "#E53935" },
    ],
    evidence: landMixEvidence(
      "Ramp = built-up share of each state's modelled land mix for the timeline year.",
    ),
    statField: null,
    landClass: "built",
  },
  {
    id: "lulc-water",
    group: "land",
    label: "Water",
    hint: "Water share of land mix, per state",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#2878D0",
    legend: [
      { label: "Lower share", color: "#d3e3f6" },
      { label: "Higher share", color: "#2878D0" },
    ],
    evidence: landMixEvidence(
      "Ramp = water share of each state's modelled land mix for the timeline year.",
    ),
    statField: null,
    landClass: "water",
  },
  {
    id: "protected",
    group: "land",
    label: "Protected areas",
    hint: "National parks, sanctuaries & ESZ boundaries",
    status: "connected",
    unavailableNote: null,
    render: "overpass",
    defaultOn: false,
    color: "#1f7a3f",
    legend: [{ label: "Protected / reserved area", color: "#1f7a3f" }],
    evidence: OSM_EVIDENCE(
      "Camera viewport only. Designation is whatever OSM carries — verify against the official sanctuary schedule before any legal use.",
    ),
    statField: null,
    landClass: null,
  },
  {
    id: "urban-expansion",
    group: "land",
    label: "Urban expansion",
    hint: "Built-up share change 2018 → selected year",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#e07b39",
    legend: [
      { label: "No / small change", color: "#efe7dc" },
      { label: "Largest increase", color: "#e07b39" },
    ],
    evidence: {
      ...landMixEvidence(
        "Difference between the modelled built-up share at 2018 and at the timeline year, per state.",
      ),
      kind: "derived",
      source: "Built-up share change 2018 → year (derived from land-scenario model)",
    },
    statField: null,
    landClass: null,
  },

  /* --------------------------------------------------------- ENVIRONMENT -- */
  {
    id: "flood-risk",
    group: "environment",
    label: "Flood risk",
    ...unavailable(
      "NDEM flood-inundation extent (1998–2022) is wired as vector tiles on the 2D maps but has no Cesium render path yet. Not connected in 3D — no flood value is drawn here.",
    ),
    render: "state-choropleth",
    defaultOn: false,
    color: "#2f6fb5",
    legend: [],
    evidence: {
      source: "NDEM historical flood inundation",
      provider: "Datameet · NDEM",
      date: "1998–2022",
      resolution: "n/a in 3D",
      coverage: "Not connected in this route",
      license: "CC0 via Datameet",
      processing: "No 3D render path — the layer is listed but disabled.",
      kind: "observed",
      confidence: "Unavailable here; use the 2D map routes for the NDEM overlay.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "seismic-risk",
    group: "environment",
    label: "Seismic risk",
    ...unavailable(
      "No licensed IS 1893 zone geometry is bundled with this project. Zone boundaries are not drawn rather than approximated.",
    ),
    render: "state-choropleth",
    defaultOn: false,
    color: "#b3402f",
    legend: [],
    evidence: {
      source: "Seismic zone map (IS 1893)",
      provider: "Not connected",
      date: "—",
      resolution: "—",
      coverage: "Not connected",
      license: "—",
      processing: "No dataset wired.",
      kind: "observed",
      confidence: "Unavailable in this route.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "climate",
    group: "environment",
    label: "Climate vulnerability",
    hint: "State vulnerability band (demo aggregate)",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#d98b09",
    legend: [
      { label: "Low", color: "#249B45" },
      { label: "Moderate", color: "#E7B84B" },
      { label: "High", color: "#C0392B" },
    ],
    evidence: stateIntelEvidence(
      "Climate vulnerability bands (STATE_STATS.risk)",
      "Each state outline is filled with its band colour; band = demo climate aggregate from state-intelligence.ts.",
      "Climate vulnerability",
    ),
    statField: "risk",
    landClass: null,
  },
  {
    id: "soil",
    group: "environment",
    label: "Soil",
    ...unavailable("No soil-map dataset is wired into this route."),
    render: "state-choropleth",
    defaultOn: false,
    color: "#8f6f3d",
    legend: [],
    evidence: {
      source: "Soil maps",
      provider: "Not connected",
      date: "—",
      resolution: "—",
      coverage: "Not connected",
      license: "—",
      processing: "No dataset wired.",
      kind: "observed",
      confidence: "Unavailable in this route.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "crop-zones",
    group: "environment",
    label: "Crop zones",
    ...unavailable("No crop-zone dataset is wired into this route."),
    render: "state-choropleth",
    defaultOn: false,
    color: "#c8a415",
    legend: [],
    evidence: {
      source: "Crop classification zones",
      provider: "Not connected",
      date: "—",
      resolution: "—",
      coverage: "Not connected",
      license: "—",
      processing: "No dataset wired.",
      kind: "observed",
      confidence: "Unavailable in this route.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "forest-esz",
    group: "environment",
    label: "Forest / ESZ",
    hint: "Reserved forests & eco-sensitive areas from OSM",
    status: "connected",
    unavailableNote: null,
    render: "overpass",
    defaultOn: false,
    color: "#1f7a3f",
    legend: [{ label: "Forest / ESZ boundary", color: "#1f7a3f" }],
    evidence: OSM_EVIDENCE(
      "Camera viewport only. Eco-sensitive-area extents follow OSM tagging and are not a notification copy.",
    ),
    statField: null,
    landClass: null,
  },
  {
    id: "crz",
    group: "environment",
    label: "CRZ",
    ...unavailable(
      "Coastal Regulation Zone notification polygons are not bundled with this project.",
    ),
    render: "state-choropleth",
    defaultOn: false,
    color: "#2878d0",
    legend: [],
    evidence: {
      source: "CRZ notification maps",
      provider: "Not connected",
      date: "—",
      resolution: "—",
      coverage: "Not connected",
      license: "—",
      processing: "No dataset wired.",
      kind: "observed",
      confidence: "Unavailable in this route.",
    },
    statField: null,
    landClass: null,
  },

  /* --------------------------------------------------------- GOVERNANCE -- */
  {
    id: "disputes",
    group: "governance",
    label: "Land disputes",
    hint: "Active dispute concentration (demo aggregate)",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#a84a3a",
    legend: [
      { label: "No significant signal", color: "#dde3d4" },
      { label: "Moderate", color: "#dfa268" },
      { label: "High", color: "#a84a3a" },
    ],
    evidence: stateIntelEvidence(
      "Dispute aggregates (STATE_STATS.disputes)",
      "State outlines are filled from the demo dispute count ramp.",
      "Active disputes",
    ),
    statField: "disputes",
    landClass: null,
  },
  {
    id: "revenue-cases",
    group: "governance",
    label: "Revenue cases",
    ...unavailable(
      "No connected revenue-case feed. Case counts are not shown rather than estimated.",
    ),
    render: "state-choropleth",
    defaultOn: false,
    color: "#8f6f3d",
    legend: [],
    evidence: {
      source: "Revenue case management records",
      provider: "Not connected",
      date: "—",
      resolution: "—",
      coverage: "Not connected",
      license: "—",
      processing: "No dataset wired.",
      kind: "observed",
      confidence: "Unavailable in this route.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "land-conversion",
    group: "governance",
    label: "Land conversion",
    hint: "Modelled agri → built-up transition pressure",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#e07b39",
    legend: [
      { label: "Low pressure", color: "#efe7dc" },
      { label: "High pressure", color: "#e07b39" },
    ],
    evidence: {
      ...landMixEvidence(
        "Modelled change in built-up share between 2018 and the timeline year, used as a conversion-pressure proxy.",
      ),
      kind: "derived",
      source: "Conversion pressure (derived from land-scenario model)",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "policy-zones",
    group: "governance",
    label: "Policy zones",
    hint: "Study-region corridors partition (modelled geometry)",
    status: "demo",
    unavailableNote: null,
    render: "study-region",
    defaultOn: false,
    color: "#5a6f8a",
    legend: [{ label: "Corridor partition", color: "#7f93ad" }],
    evidence: {
      source: "Policy study-region geography partition",
      provider: "NIRVANA (src/data/policySimulation/geographies.ts)",
      date: "Study vintage 2010–2024",
      resolution: "Corridor level",
      coverage: "One modelled study region — not an official notification area",
      license: "Modelled geometry",
      processing:
        "The partition is a deterministic, gap-free split of a study-region outline generated in code. It is a modelling convenience, not a surveyed boundary.",
      kind: "scenario",
      confidence: "Geometry is modelled. Do not read as a notified boundary.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "dev-authorities",
    group: "governance",
    label: "Development authorities",
    ...unavailable("No authority jurisdiction geometry is wired into this route."),
    render: "state-choropleth",
    defaultOn: false,
    color: "#5a6f8a",
    legend: [],
    evidence: {
      source: "Development authority jurisdictions",
      provider: "Not connected",
      date: "—",
      resolution: "—",
      coverage: "Not connected",
      license: "—",
      processing: "No dataset wired.",
      kind: "observed",
      confidence: "Unavailable in this route.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "infra-projects",
    group: "governance",
    label: "Infrastructure projects",
    ...unavailable("No project registry is wired into this route."),
    render: "state-choropleth",
    defaultOn: false,
    color: "#b08a4a",
    legend: [],
    evidence: {
      source: "Infrastructure project registry",
      provider: "Not connected",
      date: "—",
      resolution: "—",
      coverage: "Not connected",
      license: "—",
      processing: "No dataset wired.",
      kind: "observed",
      confidence: "Unavailable in this route.",
    },
    statField: null,
    landClass: null,
  },

  /* ------------------------------------------------------ SOCIOECONOMIC -- */
  {
    id: "population",
    group: "socioeconomic",
    label: "Population",
    ...unavailable(
      "No census population raster/grid is bundled. Per-state totals are not drawn as if they were gridded population.",
    ),
    render: "state-choropleth",
    defaultOn: false,
    color: "#6f7fa8",
    legend: [],
    evidence: {
      source: "Population grid",
      provider: "Not connected",
      date: "—",
      resolution: "—",
      coverage: "Not connected",
      license: "—",
      processing: "No dataset wired.",
      kind: "observed",
      confidence: "Unavailable in this route.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "urbanization",
    group: "socioeconomic",
    label: "Urbanization",
    hint: "Built-up share used as an urbanization proxy (modelled)",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#E53935",
    legend: [
      { label: "Lower built-up share", color: "#f6cfcb" },
      { label: "Higher", color: "#E53935" },
    ],
    evidence: {
      ...landMixEvidence(
        "Built-up share of each state's modelled land mix, presented as an urbanization proxy — not a census urban figure.",
      ),
      kind: "derived",
      source: "Urbanization proxy (built-up share, derived)",
    },
    statField: null,
    landClass: "built",
  },
  {
    id: "agri-dependence",
    group: "socioeconomic",
    label: "Agriculture dependence",
    hint: "Agricultural land share used as a dependence proxy",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#F6C515",
    legend: [
      { label: "Lower share", color: "#f7e6a6" },
      { label: "Higher share", color: "#F6C515" },
    ],
    evidence: {
      ...landMixEvidence(
        "Agricultural share of the modelled land mix — a land-base proxy, not a workforce statistic.",
      ),
      kind: "derived",
      source: "Agriculture dependence proxy (land share, derived)",
    },
    statField: null,
    landClass: "agri",
  },
  {
    id: "infra-access",
    group: "socioeconomic",
    label: "Infrastructure access",
    ...unavailable("No access/index dataset is wired into this route."),
    render: "state-choropleth",
    defaultOn: false,
    color: "#8a8f98",
    legend: [],
    evidence: {
      source: "Infrastructure access index",
      provider: "Not connected",
      date: "—",
      resolution: "—",
      coverage: "Not connected",
      license: "—",
      processing: "No dataset wired.",
      kind: "observed",
      confidence: "Unavailable in this route.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "socio",
    group: "socioeconomic",
    label: "Socioeconomic vulnerability",
    hint: "Share of vulnerable households (demo aggregate)",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#8f6f9f",
    legend: [
      { label: "Lower", color: "#e6dcec" },
      { label: "Higher", color: "#8f6f9f" },
    ],
    evidence: stateIntelEvidence(
      "Socio-economic overlay (STATE_STATS.socio)",
      "State outlines filled from the demo household-vulnerability aggregate.",
      "Vulnerable households",
    ),
    statField: "socio",
    landClass: null,
  },

  /* ------------------------------------------------------------- POLICY -- */
  {
    id: "policy-intervention",
    group: "policy",
    label: "Policy intervention zones",
    hint: "Corridors flagged by the policy model",
    status: "demo",
    unavailableNote: null,
    render: "study-region",
    defaultOn: false,
    color: "#2f7a5f",
    legend: [{ label: "Intervention corridor", color: "#2f7a5f" }],
    evidence: {
      source: "Policy intervention corridors",
      provider: "NIRVANA policy model (src/data/policySimulation)",
      date: "Study vintage 2010–2024",
      resolution: "Corridor level",
      coverage: "One modelled study region",
      license: "Modelled output",
      processing:
        "Growth-corridor ids resolved to the same deterministic partition geometry as policy zones.",
      kind: "scenario",
      confidence: "Modelled corridor classification.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "scenario-results",
    group: "policy",
    label: "Scenario results",
    hint: "Outputs of the policy scenario drawer",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#7f5af0",
    legend: [{ label: "Modelled outcome", color: "#7f5af0" }],
    evidence: {
      source: "Policy scenario simulation",
      provider: "NIRVANA (src/data/land-scenario.ts)",
      date: "Scenario run on demand",
      resolution: "State / UT",
      coverage: "States in the selected region",
      license: "Modelled output",
      processing:
        "Slider deltas are applied to baseline shares; only the scenario drawer's own outputs update.",
      kind: "scenario",
      confidence: "MODELLED SCENARIO — an input-response calculation, never an observation.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "did",
    group: "policy",
    label: "Difference-in-Differences",
    hint: "Treatment vs comparison difference (derived)",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#3b6fd4",
    legend: [{ label: "Treatment − comparison", color: "#3b6fd4" }],
    evidence: {
      source: "Difference-in-Differences comparison",
      provider: "NIRVANA land-scenario + state intelligence",
      date: "2018 → selected year",
      resolution: "State / UT",
      coverage: "Two selected states",
      license: "Derived from demo/modelled series",
      processing:
        "Descriptive difference of two modelled state series before and after the timeline midpoint. No parallel-trends test is run here, so the number is reported as a difference — not a causal effect.",
      kind: "derived",
      confidence:
        "Sufficiency note: with only modelled state aggregates this is a descriptive contrast. Causal language is withheld.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "before-after",
    group: "policy",
    label: "Before / after change",
    hint: "Compare two years of Sentinel-2 imagery",
    status: "connected",
    unavailableNote: null,
    render: "satellite-imagery",
    defaultOn: false,
    color: "#2f6fb5",
    legend: [],
    evidence: {
      source: "Sentinel-2 cloudless mosaics (split compare)",
      provider: "Copernicus Sentinel-2 · EOX IT Services",
      date: "Two selected years between 2018 and 2024",
      resolution: "10 m bands, rendered as tiles",
      coverage: "Global",
      license: "Free for any use with attribution (EOX)",
      processing:
        "Cesium's imagery split control renders the left year on one side of the divider and the right year on the other.",
      kind: "observed",
      confidence: "Direct comparison of two observed annual mosaics.",
    },
    statField: null,
    landClass: null,
  },
  {
    id: "policy-impact",
    group: "policy",
    label: "Policy impact",
    hint: "Scenario indicator deltas (modelled)",
    status: "demo",
    unavailableNote: null,
    render: "state-choropleth",
    defaultOn: false,
    color: "#c85a8a",
    legend: [{ label: "Modelled indicator change", color: "#c85a8a" }],
    evidence: {
      source: "Policy impact indicators",
      provider: "NIRVANA policy simulation",
      date: "Scenario run on demand",
      resolution: "State / UT",
      coverage: "Selected region",
      license: "Modelled output",
      processing: "Indicator deltas recomputed from the scenario drawer inputs.",
      kind: "scenario",
      confidence: "MODELLED SCENARIO output.",
    },
    statField: null,
    landClass: null,
  },
];

const LAYER_INDEX = new Map(GIS_LAYERS.map((l) => [l.id, l]));

export function gisLayer(id: string): GisLayerDef | undefined {
  return LAYER_INDEX.get(id);
}

export const DEFAULT_LAYER_IDS: string[] = GIS_LAYERS.filter(
  (l) => l.defaultOn && l.status !== "unavailable",
).map((l) => l.id);

/** Layers that are listed but cannot be switched on. */
export const UNAVAILABLE_LAYER_IDS: string[] = GIS_LAYERS.filter(
  (l) => l.status === "unavailable",
).map((l) => l.id);

/** True when a layer has a source we are allowed to draw. */
export function isDrawable(id: string): boolean {
  const l = LAYER_INDEX.get(id);
  return !!l && l.status !== "unavailable";
}

/** Sentinel-2 mosaic years — same list the 2D maps use. */
export const TIME_YEARS: number[] = [2018, 2019, 2020, 2021, 2022, 2023, 2024];

export const DATA_UPDATED = NOVEMBER_2024;
