/**
 * CONCEPTUAL SCENARIO ELEMENT — what a click on generated geometry reports
 * (spec §32).
 *
 * This panel is the last line of defence against a user believing a generated
 * block is a real building. It must never reuse the existing building
 * inspector's language, its fields, or its badge — a shared "Building / 18 m /
 * OSM" card would be indistinguishable from real infrastructure and would make
 * the whole SIMULATED labelling above it look decorative.
 *
 * So it states, in order: that this is conceptual, what kind of thing it is,
 * which scenario and parcel it belongs to, that it is SIMULATED, and what it is
 * for — with the disclaimer attached rather than hidden behind a disclosure.
 */

import { Layers, X } from "lucide-react";
import type { ScenarioElementKind } from "@/services/gis3d/landPotentialScenarioTypes";
import { ELEMENT_KIND_LABEL } from "@/services/gis3d/landPotentialScenarioTypes";

export interface ScenarioElementPick {
  label: string;
  kind: ScenarioElementKind;
  scenarioType: string;
  scenarioTitle: string;
  parcelId: string;
  description: string;
  purpose: string;
  disclaimer: string;
  source: string;
  modelVersion: string;
}

export function ScenarioElementInspector({
  pick,
  onClear,
  onExit,
}: {
  pick: ScenarioElementPick;
  onClear: () => void;
  onExit: () => void;
}) {
  return (
    <div className="g3d-card g3d-sc-element">
      <h3>
        <Layers /> CONCEPTUAL SCENARIO ELEMENT
        <span className="g3d-badge simulated" style={{ marginLeft: "auto" }}>
          SIMULATED
        </span>
        <button type="button" className="g3d-x" aria-label="Close" onClick={onClear}>
          <X />
        </button>
      </h3>

      <div className="g3d-stat">
        <span>Element</span>
        <b>{pick.label}</b>
      </div>
      <div className="g3d-stat">
        <span>Kind</span>
        <b>{ELEMENT_KIND_LABEL[pick.kind]}</b>
      </div>
      <div className="g3d-stat">
        <span>Scenario</span>
        <b>{pick.scenarioTitle}</b>
      </div>
      <div className="g3d-stat">
        <span>Parcel</span>
        <b>{pick.parcelId}</b>
      </div>
      <div className="g3d-stat">
        <span>Status</span>
        <b className="g3d-lp-warn">
          SIMULATED <span className="g3d-badge scenario">Conceptual</span>
        </b>
      </div>
      <div className="g3d-stat">
        <span>Purpose</span>
        <b>{pick.purpose}</b>
      </div>
      <div className="g3d-stat">
        <span>Generated by</span>
        <b>
          {pick.source} v{pick.modelVersion}
        </b>
      </div>

      <p className="g3d-hint g3d-lp-datanote">{pick.description}</p>
      <p className="g3d-lp-disclaimer">{pick.disclaimer}</p>

      <div className="g3d-actions">
        <button type="button" onClick={onExit}>
          EXIT SCENARIO
        </button>
      </div>
    </div>
  );
}
