import { INDICATORS, indicator } from "./indicators";
import { GEOGRAPHIES, GROWTH_CORRIDOR_IDS, geographiesByIds, geographyById } from "./geographies";
import type { Geography, LandCategoryId, Observation } from "./types";

/**
 * Historical observation layer.
 *
 * Values are MOCK. They are generated by one deterministic function so that the
 * land-use shares, the map, the indicator series and the simulation baseline
 * can never disagree with each other. Replace this module with a real fetch and
 * the rest of the feature is unchanged.
 */

export const BASE_YEAR = 2010;
export const ALL_YEARS: number[] = INDICATORS.reduce<number[]>((acc, i) => {
  for (let y = i.model.from; y <= i.model.to; y++) if (!acc.includes(y)) acc.push(y);
  return acc;
}, []).sort((a, b) => a - b);
export const LATEST_YEAR = ALL_YEARS[ALL_YEARS.length - 1] ?? 2024;

const CATEGORY_IDS: LandCategoryId[] = [
  "agricultural",
  "orchard",
  "forest",
  "built-up",
  "industrial",
  "water",
  "barren",
];

/** Share of each source class that responds to development pressure, per year. */
const PRESSURE_RESPONSE: Record<LandCategoryId, number> = {
  agricultural: 1,
  orchard: 0.3,
  forest: 0.06,
  "built-up": 0.05,
  industrial: 0.15,
  water: 0.1,
  barren: 0.55,
};

/** Where converted area ends up. Must sum to 1. */
const CONVERSION_SPLIT = { builtUp: 0.62, industrial: 0.11, barren: 0.27 };

const RELIEF_YEAR = 2019;
const RELIEF_FACTOR = 0.76;

const conversionRate = (geo: Geography, year: number): number => {
  const p = geo.pressure / 100;
  const base = 0.00055 + 0.0062 * Math.pow(p, 2.2);
  return year >= RELIEF_YEAR && GROWTH_CORRIDOR_IDS.includes(geo.id) ? base * RELIEF_FACTOR : base;
};

const emptyMix = (): Record<LandCategoryId, number> =>
  CATEGORY_IDS.reduce(
    (acc, id) => {
      acc[id] = 0;
      return acc;
    },
    {} as Record<LandCategoryId, number>,
  );

const normalise = (mix: Record<LandCategoryId, number>): Record<LandCategoryId, number> => {
  const sum = CATEGORY_IDS.reduce((s, id) => s + (mix[id] ?? 0), 0) || 1;
  const out = emptyMix();
  for (const id of CATEGORY_IDS) out[id] = (mix[id] ?? 0) / sum;
  return out;
};

function advance(
  mix: Record<LandCategoryId, number>,
  conv: number,
): Record<LandCategoryId, number> {
  const next = { ...mix };
  for (const id of CATEGORY_IDS) {
    const rate = conv * (PRESSURE_RESPONSE[id] ?? 0);
    if (rate <= 0) continue;
    const moved = (mix[id] ?? 0) * rate;
    next[id] = (next[id] ?? 0) - moved;
    next["built-up"] = (next["built-up"] ?? 0) + moved * CONVERSION_SPLIT.builtUp;
    next.industrial = (next.industrial ?? 0) + moved * CONVERSION_SPLIT.industrial;
    next.barren = (next.barren ?? 0) + moved * CONVERSION_SPLIT.barren;
  }
  // non-conversion transitions
  const forestLoss = (mix.forest ?? 0) * 0.0013;
  next.forest = (next.forest ?? 0) - forestLoss;
  next.barren = (next.barren ?? 0) + forestLoss;
  const waterLoss = (mix.water ?? 0) * 0.0015;
  next.water = (next.water ?? 0) - waterLoss;
  next.barren = (next.barren ?? 0) + waterLoss;
  const reclass = (mix.orchard ?? 0) * 0.0022;
  next.orchard = (next.orchard ?? 0) - reclass;
  next.agricultural = (next.agricultural ?? 0) + reclass;
  return normalise(next);
}

const mixCache = new Map<string, Record<LandCategoryId, number>>();

/** Land-use mix for a unit in a given year (the single source of truth). */
export function landMixAt(
  geoOrId: Geography | string,
  year: number,
): Record<LandCategoryId, number> {
  const geo = typeof geoOrId === "string" ? geographyById(geoOrId) : geoOrId;
  if (!geo) return normalise({ ...emptyMix(), agricultural: 1 });
  const key = `${geo.id}:${year}`;
  const hit = mixCache.get(key);
  if (hit) return hit;
  let mix: Record<LandCategoryId, number> = { ...geo.landMix };
  for (let y = BASE_YEAR; y < Math.max(BASE_YEAR, year); y++) {
    mix = advance(mix, conversionRate(geo, y));
  }
  mixCache.set(key, mix);
  return mix;
}

// ---------------------------------------------------------------------------
// Deterministic texture (so series look like measurements, not straight lines)
// ---------------------------------------------------------------------------

const hash = (s: string): number => {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return (h >>> 0) / 4294967295;
};

const wobble = (seed: number, year: number): number =>
  1 + 0.016 * Math.sin(seed * 1.7 + year * 0.62) + 0.009 * Math.sin(seed * 0.9 + year * 1.31);

// ---------------------------------------------------------------------------
// Non land-mix indicator levels
// ---------------------------------------------------------------------------

const clamp = (v: number, lo: number, hi: number) => Math.min(hi, Math.max(lo, v));

const ruralPop = (g: Geography) => g.population * (1 - g.urbanShare);
const agriAreaHa = (g: Geography, year: number) =>
  landMixAt(g, year).agricultural * g.areaKm2 * 100;

const LEVELS: Record<string, (g: Geography, year: number) => number> = {
  agri_share: (g, y) => landMixAt(g, y).agricultural * 100,
  forest_share: (g, y) => landMixAt(g, y).forest * 100,
  built_share: (g, y) => landMixAt(g, y)["built-up"] * 100,
  water_share: (g, y) => landMixAt(g, y).water * 100,
  agri_loss: (g, y) => Math.max(0, (agriAreaHa(g, y) * conversionRate(g, y)) / 100),
  crop_intensity: (g) => 96 + g.traits.irrigation * 64 - (g.pressure / 100) * 8,
  ror_digitisation: (g) => 14 + (1 - g.traits.recordBacklog) * 46,
  revenue_na_share: (g) => {
    const m = g.landMix;
    return (m["built-up"] + m.industrial + m.orchard * 0.6 + m.barren * 0.35) * 100;
  },
  parcel_mismatch: (g) => 21 + g.traits.recordBacklog * 23 - (1 - g.pressure / 100) * 7,
  parcel_count: (g) => g.areaKm2 * 0.0909,
  mutation_days: (g) => 76 - (1 - g.traits.recordBacklog) * 32 + (g.pressure / 100) * 16,
  land_value: (g) => 420 + g.traits.landMarketHeat * 4600,
  litigation_rate: (g) => 6 + g.traits.recordBacklog * 13 + (g.pressure / 100) * 5,
  acquisition_area: (g) => g.areaKm2 * (0.00016 + g.traits.projectPipeline * 0.00082),
  rr_displaced: (g) =>
    g.areaKm2 * (0.00016 + g.traits.projectPipeline * 0.00082) * 11.5 * (0.7 + g.urbanShare * 0.6),
  compensation_ratio: (g) => 60 + (1 - g.traits.recordBacklog) * 20,
  rr_compliance: (g) => 30 + (1 - g.traits.recordBacklog) * 28 - (g.pressure / 100) * 6,
  agri_per_capita: (g, y) => ((agriAreaHa(g, y) / 10000) * 10000) / Math.max(1, ruralPop(g)),
  rural_density: (g) => ruralPop(g) / g.areaKm2,
  // --- holdings structure, tenancy, planning and industry ---
  // Every indicator in the registry needs a level here. A missing entry falls
  // through to 0, which reads as a real (and very wrong) measurement rather than
  // a gap, so the set is kept exhaustive on purpose.
  holdings_avg_size: (g, y) => {
    // Mean holding = agricultural area per agricultural holding. Parcel density
    // rises with development pressure, so holdings shrink where pressure is high.
    const agriHa = landMixAt(g, y).agricultural * g.areaKm2 * 100;
    const holdingDensity = 3.1 + (g.pressure / 100) * 4.4; // holdings per km²
    return Math.max(0.15, agriHa / Math.max(1, holdingDensity * g.areaKm2));
  },
  fragment_share: (g) => clamp(38 - (g.pressure / 100) * 14 + (1 - g.traits.irrigation) * 9, 4, 62),
  tenancy_recorded: (g) =>
    clamp(18 + (1 - g.traits.recordBacklog) * 26 - (g.pressure / 100) * 12, 5, 74),
  industrial_share: (g, y) => landMixAt(g, y).industrial * 100,
  fsi: (g) => 0.85 + g.urbanShare * 1.55 + (g.pressure / 100) * 0.4,
  industrial_land_supply: (g) => g.areaKm2 * (0.004 + g.traits.projectPipeline * 0.02),
  project_pipeline: (g) => 14 + g.traits.projectPipeline * 96 + (g.pressure / 100) * 22,
};

const BOUNDS: Record<string, [number, number]> = {
  ror_digitisation: [8, 99.2],
  crop_intensity: [70, 168],
  water_share: [0.05, 12],
  compensation_ratio: [40, 400],
  rr_compliance: [12, 100],
  parcel_mismatch: [4, 70],
  industrial_share: [0.02, 22],
  fsi: [0.4, 5],
  holdings_avg_size: [0.15, 12],
  fragment_share: [3, 65],
  tenancy_recorded: [3, 80],
};

const stepFactor = (indicatorId: string, year: number): number => {
  const step = indicator(indicatorId).model.step;
  if (!step || year < step.year) return 1;
  return 1 + step.pct / 100;
};

const obsCache = new Map<string, Observation[]>();

/** Full mock series for one indicator in one unit. */
export function observationsFor(indicatorId: string, geographyId: string): Observation[] {
  const key = `${indicatorId}|${geographyId}`;
  const hit = obsCache.get(key);
  if (hit) return hit;
  const geo = geographyById(geographyId);
  const ind = indicator(indicatorId);
  if (!geo) return [];
  const level = LEVELS[indicatorId];
  const seed = hash(key) * 6.283;
  const out: Observation[] = [];
  for (let year = ind.model.from; year <= ind.model.to; year++) {
    const t = year - ind.model.from;
    const base = level ? level(geo, year) : 0;
    // Land-use series come straight out of the transition model — layering a
    // drift or breakpoint on top would double-count the same change.
    const pNorm = (geo.pressure - 50) / 50;
    const effectiveDrift = ind.model.drift * (1 + ind.model.pressureWeight * pNorm);
    const trend = ind.model.derived ? base : base * Math.pow(1 + effectiveDrift / 100, t);
    const stepped = ind.model.derived ? trend : trend * stepFactor(indicatorId, year);
    const [lo, hi] = BOUNDS[indicatorId] ?? [-Infinity, Infinity];
    const value = clamp(stepped * wobble(seed, year), lo, hi);
    out.push({ indicatorId, geographyId, year, value: Math.round(value * 1000) / 1000 });
  }
  obsCache.set(key, out);
  return out;
}

export function valueAt(indicatorId: string, geographyId: string, year: number): number | null {
  const series = observationsFor(indicatorId, geographyId);
  const exact = series.find((o) => o.year === year);
  if (exact) return exact.value;
  const before = series.filter((o) => o.year <= year).pop();
  const after = series.find((o) => o.year > year);
  if (before && after) {
    const span = after.year - before.year;
    return span <= 0
      ? before.value
      : before.value + ((after.value - before.value) * (year - before.year)) / span;
  }
  return before?.value ?? after?.value ?? null;
}

// ---------------------------------------------------------------------------
// Aggregation across units
// ---------------------------------------------------------------------------

type Aggregator = (units: Geography[], year: number) => number;

const parcelUnits = (g: Geography) => g.areaKm2 * 0.0909;
const totalArea = (units: Geography[]) => units.reduce((s, g) => s + g.areaKm2, 0);
const totalRural = (units: Geography[]) => units.reduce((s, g) => s + ruralPop(g), 0);

/** Weighted mean of an indicator across units (weight chosen per indicator). */
const weighted =
  (id: string, weight: (g: Geography) => number): Aggregator =>
  (units, year) => {
    const total = units.reduce((s, g) => s + weight(g), 0) || 1;
    return units.reduce((sum, g) => sum + (valueAt(id, g.id, year) ?? 0) * weight(g), 0) / total;
  };

/** Totals only make sense when summed across units (area, parcels, families). */
const summed =
  (id: string): Aggregator =>
  (units, year) =>
    units.reduce((s, g) => s + (valueAt(id, g.id, year) ?? 0), 0);

const AGGREGATORS: Record<string, Aggregator> = {
  agri_share: weighted("agri_share", (g) => g.areaKm2),
  forest_share: weighted("forest_share", (g) => g.areaKm2),
  built_share: weighted("built_share", (g) => g.areaKm2),
  water_share: weighted("water_share", (g) => g.areaKm2),
  agri_loss: weighted("agri_loss", (g) => g.areaKm2),
  crop_intensity: weighted("crop_intensity", (g) => g.areaKm2),
  ror_digitisation: weighted("ror_digitisation", (g) => g.population),
  revenue_na_share: weighted("revenue_na_share", (g) => g.areaKm2),
  parcel_mismatch: weighted("parcel_mismatch", parcelUnits),
  parcel_count: summed("parcel_count"),
  mutation_days: weighted("mutation_days", (g) => g.population),
  land_value: weighted("land_value", (g) => g.areaKm2),
  litigation_rate: weighted("litigation_rate", parcelUnits),
  acquisition_area: summed("acquisition_area"),
  rr_displaced: summed("rr_displaced"),
  compensation_ratio: weighted("compensation_ratio", (g) => g.areaKm2),
  rr_compliance: weighted("rr_compliance", (g) => g.areaKm2),
  agri_per_capita: (units: Geography[], year: number) => {
    const ha = units.reduce((s, g) => s + agriAreaHa(g, year), 0);
    return ha / Math.max(1, totalRural(units));
  },
  rural_density: (units: Geography[]) => totalRural(units) / (totalArea(units) || 1),
};

/** Area/population weighted value of an indicator across units, in a year. */
export function aggregateValue(
  indicatorId: string,
  geographyIds: string[],
  year = LATEST_YEAR,
): number | null {
  const units = geographiesByIds(geographyIds);
  if (!units.length) return null;
  if (!observationsFor(indicatorId, units[0]?.id ?? "").length) return null;
  const agg = AGGREGATORS[indicatorId] ?? weighted(indicatorId, (g) => g.areaKm2);
  return agg(units, year);
}

/** Indicator series across a set of units. */
export function aggregateSeries(indicatorId: string, geographyIds: string[]): Observation[] {
  const units = geographiesByIds(geographyIds);
  if (!units.length) return [];
  const ind = indicator(indicatorId);
  const agg = AGGREGATORS[indicatorId] ?? weighted(indicatorId, (g) => g.areaKm2);
  const out: Observation[] = [];
  for (let y = ind.model.from; y <= ind.model.to; y++) {
    out.push({
      indicatorId,
      geographyId: `agg:${geographyIds.join("|")}`,
      year: y,
      value: agg(units, y),
    });
  }
  return out;
}

/** Land-use mix aggregated across units, in a year. */
export function aggregateLandMixAt(
  geographyIds: string[],
  year: number,
): Record<LandCategoryId, number> {
  const units = geographiesByIds(geographyIds);
  const total = units.reduce((s, g) => s + g.areaKm2, 0) || 1;
  const out = emptyMix();
  for (const id of CATEGORY_IDS) {
    out[id] = units.reduce((s, g) => s + landMixAt(g, year)[id] * g.areaKm2, 0) / total;
  }
  return out;
}

/** Mean of an indicator across a window of years. */
export function meanOverWindow(
  indicatorId: string,
  geographyIds: string[],
  from: number,
  to: number,
): number | null {
  const series = aggregateSeries(indicatorId, geographyIds);
  const inRange = series.filter((o) => o.year >= from && o.year <= to);
  if (!inRange.length) return null;
  return inRange.reduce((s, o) => s + o.value, 0) / inRange.length;
}

/** Number of mock observations the layer can produce (indicators x units x years). */
export function observationCount(): number {
  return INDICATORS.reduce(
    (sum, i) => sum + (i.model.to - i.model.from + 1) * GEOGRAPHIES.length,
    0,
  );
}
