/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GisExplorerRouteImport } from './routes/gis-explorer'
import { Route as InnovationPortalRouteImport } from './routes/innovation-portal'
import { Route as LanddifferenceRouteImport } from './routes/landdifference'
import { Route as RecordVsRealityRouteImport } from './routes/record-vs-reality'
import { Route as ResearchHubRouteImport } from './routes/research-hub'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GisExplorerRoute = GisExplorerRouteImport.update({
  id: '/gis-explorer',
  path: '/gis-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationPortalRoute = InnovationPortalRouteImport.update({
  id: '/innovation-portal',
  path: '/innovation-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LanddifferenceRoute = LanddifferenceRouteImport.update({
  id: '/landdifference',
  path: '/landdifference',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordVsRealityRoute = RecordVsRealityRouteImport.update({
  id: '/record-vs-reality',
  path: '/record-vs-reality',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchHubRoute = ResearchHubRouteImport.update({
  id: '/research-hub',
  path: '/research-hub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gis-explorer': typeof GisExplorerRoute
  '/innovation-portal': typeof InnovationPortalRoute
  '/landdifference': typeof LanddifferenceRoute
  '/record-vs-reality': typeof RecordVsRealityRoute
  '/research-hub': typeof ResearchHubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gis-explorer': typeof GisExplorerRoute
  '/innovation-portal': typeof InnovationPortalRoute
  '/landdifference': typeof LanddifferenceRoute
  '/record-vs-reality': typeof RecordVsRealityRoute
  '/research-hub': typeof ResearchHubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gis-explorer': typeof GisExplorerRoute
  '/innovation-portal': typeof InnovationPortalRoute
  '/landdifference': typeof LanddifferenceRoute
  '/record-vs-reality': typeof RecordVsRealityRoute
  '/research-hub': typeof ResearchHubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/gis-explorer'
    | '/innovation-portal'
    | '/landdifference'
    | '/record-vs-reality'
    | '/research-hub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/gis-explorer'
    | '/innovation-portal'
    | '/landdifference'
    | '/record-vs-reality'
    | '/research-hub'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/gis-explorer'
    | '/innovation-portal'
    | '/landdifference'
    | '/record-vs-reality'
    | '/research-hub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GisExplorerRoute: typeof GisExplorerRoute
  InnovationPortalRoute: typeof InnovationPortalRoute
  LanddifferenceRoute: typeof LanddifferenceRoute
  RecordVsRealityRoute: typeof RecordVsRealityRoute
  ResearchHubRoute: typeof ResearchHubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis-explorer': {
      id: '/gis-explorer'
      path: '/gis-explorer'
      fullPath: '/gis-explorer'
      preLoaderRoute: typeof GisExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation-portal': {
      id: '/innovation-portal'
      path: '/innovation-portal'
      fullPath: '/innovation-portal'
      preLoaderRoute: typeof InnovationPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landdifference': {
      id: '/landdifference'
      path: '/landdifference'
      fullPath: '/landdifference'
      preLoaderRoute: typeof LanddifferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record-vs-reality': {
      id: '/record-vs-reality'
      path: '/record-vs-reality'
      fullPath: '/record-vs-reality'
      preLoaderRoute: typeof RecordVsRealityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-hub': {
      id: '/research-hub'
      path: '/research-hub'
      fullPath: '/research-hub'
      preLoaderRoute: typeof ResearchHubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GisExplorerRoute: GisExplorerRoute,
  InnovationPortalRoute: InnovationPortalRoute,
  LanddifferenceRoute: LanddifferenceRoute,
  RecordVsRealityRoute: RecordVsRealityRoute,
  ResearchHubRoute: ResearchHubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
