/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChooseRoleRouteImport } from './routes/choose-role'
import { Route as CollaborativehubRouteImport } from './routes/collaborativehub'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataApisRouteImport } from './routes/data-apis'
import { Route as FederationConsoleRouteImport } from './routes/federation-console'
import { Route as GisExplorerRouteImport } from './routes/gis-explorer'
import { Route as GisExplorer3dRouteImport } from './routes/gis-explorer-3d'
import { Route as ImpactMonitoringRouteImport } from './routes/impact-monitoring'
import { Route as InnovationPortalRouteImport } from './routes/innovation-portal'
import { Route as LanddifferenceRouteImport } from './routes/landdifference'
import { Route as MyTasksRouteImport } from './routes/my-tasks'
import { Route as ParcelRouteImport } from './routes/parcel'
import { Route as PolicyLabRouteImport } from './routes/policy-lab'
import { Route as RecordVsRealityRouteImport } from './routes/record-vs-reality'
import { Route as ReportMismatchRouteImport } from './routes/report-mismatch'
import { Route as ReportStatusRouteImport } from './routes/report-status'
import { Route as ResearchHubRouteImport } from './routes/research-hub'
import { Route as TimeMachineRouteImport } from './routes/time-machine'
import { Route as VerificationQueueRouteImport } from './routes/verification-queue'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as InnovationIndexRouteImport } from './routes/innovation/index'
import { Route as InnovationImpactRouteImport } from './routes/innovation/impact'
import { Route as InnovationPilotsRouteImport } from './routes/innovation/pilots'
import { Route as InnovationSubmitRouteImport } from './routes/innovation/submit'
import { Route as InnovationChallengesIndexRouteImport } from './routes/innovation/challenges/index'
import { Route as InnovationChallengesChallengeIdRouteImport } from './routes/innovation/challenges/$challengeId'
import { Route as InnovationWorkspaceProjectIdRouteImport } from './routes/innovation/workspace/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoleRoute = ChooseRoleRouteImport.update({
  id: '/choose-role',
  path: '/choose-role',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborativehubRoute = CollaborativehubRouteImport.update({
  id: '/collaborativehub',
  path: '/collaborativehub',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataApisRoute = DataApisRouteImport.update({
  id: '/data-apis',
  path: '/data-apis',
  getParentRoute: () => rootRouteImport,
} as any)
const FederationConsoleRoute = FederationConsoleRouteImport.update({
  id: '/federation-console',
  path: '/federation-console',
  getParentRoute: () => rootRouteImport,
} as any)
const GisExplorerRoute = GisExplorerRouteImport.update({
  id: '/gis-explorer',
  path: '/gis-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const GisExplorer3dRoute = GisExplorer3dRouteImport.update({
  id: '/gis-explorer-3d',
  path: '/gis-explorer-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactMonitoringRoute = ImpactMonitoringRouteImport.update({
  id: '/impact-monitoring',
  path: '/impact-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationPortalRoute = InnovationPortalRouteImport.update({
  id: '/innovation-portal',
  path: '/innovation-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LanddifferenceRoute = LanddifferenceRouteImport.update({
  id: '/landdifference',
  path: '/landdifference',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTasksRoute = MyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelRoute = ParcelRouteImport.update({
  id: '/parcel',
  path: '/parcel',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyLabRoute = PolicyLabRouteImport.update({
  id: '/policy-lab',
  path: '/policy-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordVsRealityRoute = RecordVsRealityRouteImport.update({
  id: '/record-vs-reality',
  path: '/record-vs-reality',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportMismatchRoute = ReportMismatchRouteImport.update({
  id: '/report-mismatch',
  path: '/report-mismatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportStatusRoute = ReportStatusRouteImport.update({
  id: '/report-status',
  path: '/report-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchHubRoute = ResearchHubRouteImport.update({
  id: '/research-hub',
  path: '/research-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeMachineRoute = TimeMachineRouteImport.update({
  id: '/time-machine',
  path: '/time-machine',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationQueueRoute = VerificationQueueRouteImport.update({
  id: '/verification-queue',
  path: '/verification-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationIndexRoute = InnovationIndexRouteImport.update({
  id: '/innovation/',
  path: '/innovation/',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationImpactRoute = InnovationImpactRouteImport.update({
  id: '/innovation/impact',
  path: '/innovation/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationPilotsRoute = InnovationPilotsRouteImport.update({
  id: '/innovation/pilots',
  path: '/innovation/pilots',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationSubmitRoute = InnovationSubmitRouteImport.update({
  id: '/innovation/submit',
  path: '/innovation/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationChallengesIndexRoute =
  InnovationChallengesIndexRouteImport.update({
    id: '/innovation/challenges/',
    path: '/innovation/challenges/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InnovationChallengesChallengeIdRoute =
  InnovationChallengesChallengeIdRouteImport.update({
    id: '/innovation/challenges/$challengeId',
    path: '/innovation/challenges/$challengeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InnovationWorkspaceProjectIdRoute =
  InnovationWorkspaceProjectIdRouteImport.update({
    id: '/innovation/workspace/$projectId',
    path: '/innovation/workspace/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choose-role': typeof ChooseRoleRoute
  '/collaborativehub': typeof CollaborativehubRoute
  '/consultations': typeof ConsultationsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/data-apis': typeof DataApisRoute
  '/federation-console': typeof FederationConsoleRoute
  '/gis-explorer': typeof GisExplorerRoute
  '/gis-explorer-3d': typeof GisExplorer3dRoute
  '/impact-monitoring': typeof ImpactMonitoringRoute
  '/innovation-portal': typeof InnovationPortalRoute
  '/landdifference': typeof LanddifferenceRoute
  '/my-tasks': typeof MyTasksRoute
  '/parcel': typeof ParcelRoute
  '/policy-lab': typeof PolicyLabRoute
  '/record-vs-reality': typeof RecordVsRealityRoute
  '/report-mismatch': typeof ReportMismatchRoute
  '/report-status': typeof ReportStatusRoute
  '/research-hub': typeof ResearchHubRoute
  '/time-machine': typeof TimeMachineRoute
  '/verification-queue': typeof VerificationQueueRoute
  '/workflow': typeof WorkflowRoute
  '/innovation/impact': typeof InnovationImpactRoute
  '/innovation/pilots': typeof InnovationPilotsRoute
  '/innovation/submit': typeof InnovationSubmitRoute
  '/innovation/': typeof InnovationIndexRoute
  '/innovation/challenges/$challengeId': typeof InnovationChallengesChallengeIdRoute
  '/innovation/workspace/$projectId': typeof InnovationWorkspaceProjectIdRoute
  '/innovation/challenges/': typeof InnovationChallengesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-role': typeof ChooseRoleRoute
  '/collaborativehub': typeof CollaborativehubRoute
  '/consultations': typeof ConsultationsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/data-apis': typeof DataApisRoute
  '/federation-console': typeof FederationConsoleRoute
  '/gis-explorer': typeof GisExplorerRoute
  '/gis-explorer-3d': typeof GisExplorer3dRoute
  '/impact-monitoring': typeof ImpactMonitoringRoute
  '/innovation-portal': typeof InnovationPortalRoute
  '/landdifference': typeof LanddifferenceRoute
  '/my-tasks': typeof MyTasksRoute
  '/parcel': typeof ParcelRoute
  '/policy-lab': typeof PolicyLabRoute
  '/record-vs-reality': typeof RecordVsRealityRoute
  '/report-mismatch': typeof ReportMismatchRoute
  '/report-status': typeof ReportStatusRoute
  '/research-hub': typeof ResearchHubRoute
  '/time-machine': typeof TimeMachineRoute
  '/verification-queue': typeof VerificationQueueRoute
  '/workflow': typeof WorkflowRoute
  '/innovation/impact': typeof InnovationImpactRoute
  '/innovation/pilots': typeof InnovationPilotsRoute
  '/innovation/submit': typeof InnovationSubmitRoute
  '/innovation': typeof InnovationIndexRoute
  '/innovation/challenges/$challengeId': typeof InnovationChallengesChallengeIdRoute
  '/innovation/workspace/$projectId': typeof InnovationWorkspaceProjectIdRoute
  '/innovation/challenges': typeof InnovationChallengesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/choose-role': typeof ChooseRoleRoute
  '/collaborativehub': typeof CollaborativehubRoute
  '/consultations': typeof ConsultationsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/data-apis': typeof DataApisRoute
  '/federation-console': typeof FederationConsoleRoute
  '/gis-explorer': typeof GisExplorerRoute
  '/gis-explorer-3d': typeof GisExplorer3dRoute
  '/impact-monitoring': typeof ImpactMonitoringRoute
  '/innovation-portal': typeof InnovationPortalRoute
  '/landdifference': typeof LanddifferenceRoute
  '/my-tasks': typeof MyTasksRoute
  '/parcel': typeof ParcelRoute
  '/policy-lab': typeof PolicyLabRoute
  '/record-vs-reality': typeof RecordVsRealityRoute
  '/report-mismatch': typeof ReportMismatchRoute
  '/report-status': typeof ReportStatusRoute
  '/research-hub': typeof ResearchHubRoute
  '/time-machine': typeof TimeMachineRoute
  '/verification-queue': typeof VerificationQueueRoute
  '/workflow': typeof WorkflowRoute
  '/innovation/impact': typeof InnovationImpactRoute
  '/innovation/pilots': typeof InnovationPilotsRoute
  '/innovation/submit': typeof InnovationSubmitRoute
  '/innovation/': typeof InnovationIndexRoute
  '/innovation/challenges/$challengeId': typeof InnovationChallengesChallengeIdRoute
  '/innovation/workspace/$projectId': typeof InnovationWorkspaceProjectIdRoute
  '/innovation/challenges/': typeof InnovationChallengesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/choose-role'
    | '/collaborativehub'
    | '/consultations'
    | '/copilot'
    | '/dashboard'
    | '/data-apis'
    | '/federation-console'
    | '/gis-explorer'
    | '/gis-explorer-3d'
    | '/impact-monitoring'
    | '/innovation-portal'
    | '/landdifference'
    | '/my-tasks'
    | '/parcel'
    | '/policy-lab'
    | '/record-vs-reality'
    | '/report-mismatch'
    | '/report-status'
    | '/research-hub'
    | '/time-machine'
    | '/verification-queue'
    | '/workflow'
    | '/innovation/impact'
    | '/innovation/pilots'
    | '/innovation/submit'
    | '/innovation/'
    | '/innovation/challenges/$challengeId'
    | '/innovation/workspace/$projectId'
    | '/innovation/challenges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choose-role'
    | '/collaborativehub'
    | '/consultations'
    | '/copilot'
    | '/dashboard'
    | '/data-apis'
    | '/federation-console'
    | '/gis-explorer'
    | '/gis-explorer-3d'
    | '/impact-monitoring'
    | '/innovation-portal'
    | '/landdifference'
    | '/my-tasks'
    | '/parcel'
    | '/policy-lab'
    | '/record-vs-reality'
    | '/report-mismatch'
    | '/report-status'
    | '/research-hub'
    | '/time-machine'
    | '/verification-queue'
    | '/workflow'
    | '/innovation/impact'
    | '/innovation/pilots'
    | '/innovation/submit'
    | '/innovation'
    | '/innovation/challenges/$challengeId'
    | '/innovation/workspace/$projectId'
    | '/innovation/challenges'
  id:
    | '__root__'
    | '/'
    | '/choose-role'
    | '/collaborativehub'
    | '/consultations'
    | '/copilot'
    | '/dashboard'
    | '/data-apis'
    | '/federation-console'
    | '/gis-explorer'
    | '/gis-explorer-3d'
    | '/impact-monitoring'
    | '/innovation-portal'
    | '/landdifference'
    | '/my-tasks'
    | '/parcel'
    | '/policy-lab'
    | '/record-vs-reality'
    | '/report-mismatch'
    | '/report-status'
    | '/research-hub'
    | '/time-machine'
    | '/verification-queue'
    | '/workflow'
    | '/innovation/impact'
    | '/innovation/pilots'
    | '/innovation/submit'
    | '/innovation/'
    | '/innovation/challenges/$challengeId'
    | '/innovation/workspace/$projectId'
    | '/innovation/challenges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChooseRoleRoute: typeof ChooseRoleRoute
  CollaborativehubRoute: typeof CollaborativehubRoute
  ConsultationsRoute: typeof ConsultationsRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DataApisRoute: typeof DataApisRoute
  FederationConsoleRoute: typeof FederationConsoleRoute
  GisExplorerRoute: typeof GisExplorerRoute
  GisExplorer3dRoute: typeof GisExplorer3dRoute
  ImpactMonitoringRoute: typeof ImpactMonitoringRoute
  InnovationPortalRoute: typeof InnovationPortalRoute
  LanddifferenceRoute: typeof LanddifferenceRoute
  MyTasksRoute: typeof MyTasksRoute
  ParcelRoute: typeof ParcelRoute
  PolicyLabRoute: typeof PolicyLabRoute
  RecordVsRealityRoute: typeof RecordVsRealityRoute
  ReportMismatchRoute: typeof ReportMismatchRoute
  ReportStatusRoute: typeof ReportStatusRoute
  ResearchHubRoute: typeof ResearchHubRoute
  TimeMachineRoute: typeof TimeMachineRoute
  VerificationQueueRoute: typeof VerificationQueueRoute
  WorkflowRoute: typeof WorkflowRoute
  InnovationImpactRoute: typeof InnovationImpactRoute
  InnovationPilotsRoute: typeof InnovationPilotsRoute
  InnovationSubmitRoute: typeof InnovationSubmitRoute
  InnovationIndexRoute: typeof InnovationIndexRoute
  InnovationChallengesChallengeIdRoute: typeof InnovationChallengesChallengeIdRoute
  InnovationWorkspaceProjectIdRoute: typeof InnovationWorkspaceProjectIdRoute
  InnovationChallengesIndexRoute: typeof InnovationChallengesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-role': {
      id: '/choose-role'
      path: '/choose-role'
      fullPath: '/choose-role'
      preLoaderRoute: typeof ChooseRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborativehub': {
      id: '/collaborativehub'
      path: '/collaborativehub'
      fullPath: '/collaborativehub'
      preLoaderRoute: typeof CollaborativehubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-apis': {
      id: '/data-apis'
      path: '/data-apis'
      fullPath: '/data-apis'
      preLoaderRoute: typeof DataApisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federation-console': {
      id: '/federation-console'
      path: '/federation-console'
      fullPath: '/federation-console'
      preLoaderRoute: typeof FederationConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis-explorer': {
      id: '/gis-explorer'
      path: '/gis-explorer'
      fullPath: '/gis-explorer'
      preLoaderRoute: typeof GisExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis-explorer-3d': {
      id: '/gis-explorer-3d'
      path: '/gis-explorer-3d'
      fullPath: '/gis-explorer-3d'
      preLoaderRoute: typeof GisExplorer3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact-monitoring': {
      id: '/impact-monitoring'
      path: '/impact-monitoring'
      fullPath: '/impact-monitoring'
      preLoaderRoute: typeof ImpactMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation-portal': {
      id: '/innovation-portal'
      path: '/innovation-portal'
      fullPath: '/innovation-portal'
      preLoaderRoute: typeof InnovationPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landdifference': {
      id: '/landdifference'
      path: '/landdifference'
      fullPath: '/landdifference'
      preLoaderRoute: typeof LanddifferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tasks': {
      id: '/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof MyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcel': {
      id: '/parcel'
      path: '/parcel'
      fullPath: '/parcel'
      preLoaderRoute: typeof ParcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-lab': {
      id: '/policy-lab'
      path: '/policy-lab'
      fullPath: '/policy-lab'
      preLoaderRoute: typeof PolicyLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record-vs-reality': {
      id: '/record-vs-reality'
      path: '/record-vs-reality'
      fullPath: '/record-vs-reality'
      preLoaderRoute: typeof RecordVsRealityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-mismatch': {
      id: '/report-mismatch'
      path: '/report-mismatch'
      fullPath: '/report-mismatch'
      preLoaderRoute: typeof ReportMismatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-status': {
      id: '/report-status'
      path: '/report-status'
      fullPath: '/report-status'
      preLoaderRoute: typeof ReportStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-hub': {
      id: '/research-hub'
      path: '/research-hub'
      fullPath: '/research-hub'
      preLoaderRoute: typeof ResearchHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-machine': {
      id: '/time-machine'
      path: '/time-machine'
      fullPath: '/time-machine'
      preLoaderRoute: typeof TimeMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-queue': {
      id: '/verification-queue'
      path: '/verification-queue'
      fullPath: '/verification-queue'
      preLoaderRoute: typeof VerificationQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/': {
      id: '/innovation/'
      path: '/innovation'
      fullPath: '/innovation/'
      preLoaderRoute: typeof InnovationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/impact': {
      id: '/innovation/impact'
      path: '/innovation/impact'
      fullPath: '/innovation/impact'
      preLoaderRoute: typeof InnovationImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/pilots': {
      id: '/innovation/pilots'
      path: '/innovation/pilots'
      fullPath: '/innovation/pilots'
      preLoaderRoute: typeof InnovationPilotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/submit': {
      id: '/innovation/submit'
      path: '/innovation/submit'
      fullPath: '/innovation/submit'
      preLoaderRoute: typeof InnovationSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/challenges/': {
      id: '/innovation/challenges/'
      path: '/innovation/challenges'
      fullPath: '/innovation/challenges/'
      preLoaderRoute: typeof InnovationChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/challenges/$challengeId': {
      id: '/innovation/challenges/$challengeId'
      path: '/innovation/challenges/$challengeId'
      fullPath: '/innovation/challenges/$challengeId'
      preLoaderRoute: typeof InnovationChallengesChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/workspace/$projectId': {
      id: '/innovation/workspace/$projectId'
      path: '/innovation/workspace/$projectId'
      fullPath: '/innovation/workspace/$projectId'
      preLoaderRoute: typeof InnovationWorkspaceProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChooseRoleRoute: ChooseRoleRoute,
  CollaborativehubRoute: CollaborativehubRoute,
  ConsultationsRoute: ConsultationsRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DataApisRoute: DataApisRoute,
  FederationConsoleRoute: FederationConsoleRoute,
  GisExplorerRoute: GisExplorerRoute,
  GisExplorer3dRoute: GisExplorer3dRoute,
  ImpactMonitoringRoute: ImpactMonitoringRoute,
  InnovationPortalRoute: InnovationPortalRoute,
  LanddifferenceRoute: LanddifferenceRoute,
  MyTasksRoute: MyTasksRoute,
  ParcelRoute: ParcelRoute,
  PolicyLabRoute: PolicyLabRoute,
  RecordVsRealityRoute: RecordVsRealityRoute,
  ReportMismatchRoute: ReportMismatchRoute,
  ReportStatusRoute: ReportStatusRoute,
  ResearchHubRoute: ResearchHubRoute,
  TimeMachineRoute: TimeMachineRoute,
  VerificationQueueRoute: VerificationQueueRoute,
  WorkflowRoute: WorkflowRoute,
  InnovationImpactRoute: InnovationImpactRoute,
  InnovationPilotsRoute: InnovationPilotsRoute,
  InnovationSubmitRoute: InnovationSubmitRoute,
  InnovationIndexRoute: InnovationIndexRoute,
  InnovationChallengesChallengeIdRoute: InnovationChallengesChallengeIdRoute,
  InnovationWorkspaceProjectIdRoute: InnovationWorkspaceProjectIdRoute,
  InnovationChallengesIndexRoute: InnovationChallengesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
