/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollaborativehubRouteImport } from './routes/collaborativehub'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GisExplorerRouteImport } from './routes/gis-explorer'
import { Route as GisExplorer3dRouteImport } from './routes/gis-explorer-3d'
import { Route as InnovationPortalRouteImport } from './routes/innovation-portal'
import { Route as LanddifferenceRouteImport } from './routes/landdifference'
import { Route as PolicyLabRouteImport } from './routes/policy-lab'
import { Route as RecordVsRealityRouteImport } from './routes/record-vs-reality'
import { Route as ResearchHubRouteImport } from './routes/research-hub'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as InnovationIndexRouteImport } from './routes/innovation/index'
import { Route as InnovationImpactRouteImport } from './routes/innovation/impact'
import { Route as InnovationPilotsRouteImport } from './routes/innovation/pilots'
import { Route as InnovationSubmitRouteImport } from './routes/innovation/submit'
import { Route as InnovationChallengesIndexRouteImport } from './routes/innovation/challenges/index'
import { Route as InnovationChallengesChallengeIdRouteImport } from './routes/innovation/challenges/$challengeId'
import { Route as InnovationWorkspaceProjectIdRouteImport } from './routes/innovation/workspace/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborativehubRoute = CollaborativehubRouteImport.update({
  id: '/collaborativehub',
  path: '/collaborativehub',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GisExplorerRoute = GisExplorerRouteImport.update({
  id: '/gis-explorer',
  path: '/gis-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const GisExplorer3dRoute = GisExplorer3dRouteImport.update({
  id: '/gis-explorer-3d',
  path: '/gis-explorer-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationPortalRoute = InnovationPortalRouteImport.update({
  id: '/innovation-portal',
  path: '/innovation-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LanddifferenceRoute = LanddifferenceRouteImport.update({
  id: '/landdifference',
  path: '/landdifference',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyLabRoute = PolicyLabRouteImport.update({
  id: '/policy-lab',
  path: '/policy-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordVsRealityRoute = RecordVsRealityRouteImport.update({
  id: '/record-vs-reality',
  path: '/record-vs-reality',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchHubRoute = ResearchHubRouteImport.update({
  id: '/research-hub',
  path: '/research-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationIndexRoute = InnovationIndexRouteImport.update({
  id: '/innovation/',
  path: '/innovation/',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationImpactRoute = InnovationImpactRouteImport.update({
  id: '/innovation/impact',
  path: '/innovation/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationPilotsRoute = InnovationPilotsRouteImport.update({
  id: '/innovation/pilots',
  path: '/innovation/pilots',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationSubmitRoute = InnovationSubmitRouteImport.update({
  id: '/innovation/submit',
  path: '/innovation/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationChallengesIndexRoute =
  InnovationChallengesIndexRouteImport.update({
    id: '/innovation/challenges/',
    path: '/innovation/challenges/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InnovationChallengesChallengeIdRoute =
  InnovationChallengesChallengeIdRouteImport.update({
    id: '/innovation/challenges/$challengeId',
    path: '/innovation/challenges/$challengeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InnovationWorkspaceProjectIdRoute =
  InnovationWorkspaceProjectIdRouteImport.update({
    id: '/innovation/workspace/$projectId',
    path: '/innovation/workspace/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collaborativehub': typeof CollaborativehubRoute
  '/dashboard': typeof DashboardRoute
  '/gis-explorer': typeof GisExplorerRoute
  '/gis-explorer-3d': typeof GisExplorer3dRoute
  '/innovation-portal': typeof InnovationPortalRoute
  '/landdifference': typeof LanddifferenceRoute
  '/policy-lab': typeof PolicyLabRoute
  '/record-vs-reality': typeof RecordVsRealityRoute
  '/research-hub': typeof ResearchHubRoute
  '/workflow': typeof WorkflowRoute
  '/innovation/impact': typeof InnovationImpactRoute
  '/innovation/pilots': typeof InnovationPilotsRoute
  '/innovation/submit': typeof InnovationSubmitRoute
  '/innovation/': typeof InnovationIndexRoute
  '/innovation/challenges/$challengeId': typeof InnovationChallengesChallengeIdRoute
  '/innovation/workspace/$projectId': typeof InnovationWorkspaceProjectIdRoute
  '/innovation/challenges/': typeof InnovationChallengesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collaborativehub': typeof CollaborativehubRoute
  '/dashboard': typeof DashboardRoute
  '/gis-explorer': typeof GisExplorerRoute
  '/gis-explorer-3d': typeof GisExplorer3dRoute
  '/innovation-portal': typeof InnovationPortalRoute
  '/landdifference': typeof LanddifferenceRoute
  '/policy-lab': typeof PolicyLabRoute
  '/record-vs-reality': typeof RecordVsRealityRoute
  '/research-hub': typeof ResearchHubRoute
  '/workflow': typeof WorkflowRoute
  '/innovation/impact': typeof InnovationImpactRoute
  '/innovation/pilots': typeof InnovationPilotsRoute
  '/innovation/submit': typeof InnovationSubmitRoute
  '/innovation': typeof InnovationIndexRoute
  '/innovation/challenges/$challengeId': typeof InnovationChallengesChallengeIdRoute
  '/innovation/workspace/$projectId': typeof InnovationWorkspaceProjectIdRoute
  '/innovation/challenges': typeof InnovationChallengesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collaborativehub': typeof CollaborativehubRoute
  '/dashboard': typeof DashboardRoute
  '/gis-explorer': typeof GisExplorerRoute
  '/gis-explorer-3d': typeof GisExplorer3dRoute
  '/innovation-portal': typeof InnovationPortalRoute
  '/landdifference': typeof LanddifferenceRoute
  '/policy-lab': typeof PolicyLabRoute
  '/record-vs-reality': typeof RecordVsRealityRoute
  '/research-hub': typeof ResearchHubRoute
  '/workflow': typeof WorkflowRoute
  '/innovation/impact': typeof InnovationImpactRoute
  '/innovation/pilots': typeof InnovationPilotsRoute
  '/innovation/submit': typeof InnovationSubmitRoute
  '/innovation/': typeof InnovationIndexRoute
  '/innovation/challenges/$challengeId': typeof InnovationChallengesChallengeIdRoute
  '/innovation/workspace/$projectId': typeof InnovationWorkspaceProjectIdRoute
  '/innovation/challenges/': typeof InnovationChallengesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collaborativehub'
    | '/dashboard'
    | '/gis-explorer'
    | '/gis-explorer-3d'
    | '/innovation-portal'
    | '/landdifference'
    | '/policy-lab'
    | '/record-vs-reality'
    | '/research-hub'
    | '/workflow'
    | '/innovation/impact'
    | '/innovation/pilots'
    | '/innovation/submit'
    | '/innovation/'
    | '/innovation/challenges/$challengeId'
    | '/innovation/workspace/$projectId'
    | '/innovation/challenges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collaborativehub'
    | '/dashboard'
    | '/gis-explorer'
    | '/gis-explorer-3d'
    | '/innovation-portal'
    | '/landdifference'
    | '/policy-lab'
    | '/record-vs-reality'
    | '/research-hub'
    | '/workflow'
    | '/innovation/impact'
    | '/innovation/pilots'
    | '/innovation/submit'
    | '/innovation'
    | '/innovation/challenges/$challengeId'
    | '/innovation/workspace/$projectId'
    | '/innovation/challenges'
  id:
    | '__root__'
    | '/'
    | '/collaborativehub'
    | '/dashboard'
    | '/gis-explorer'
    | '/gis-explorer-3d'
    | '/innovation-portal'
    | '/landdifference'
    | '/policy-lab'
    | '/record-vs-reality'
    | '/research-hub'
    | '/workflow'
    | '/innovation/impact'
    | '/innovation/pilots'
    | '/innovation/submit'
    | '/innovation/'
    | '/innovation/challenges/$challengeId'
    | '/innovation/workspace/$projectId'
    | '/innovation/challenges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollaborativehubRoute: typeof CollaborativehubRoute
  DashboardRoute: typeof DashboardRoute
  GisExplorerRoute: typeof GisExplorerRoute
  GisExplorer3dRoute: typeof GisExplorer3dRoute
  InnovationPortalRoute: typeof InnovationPortalRoute
  LanddifferenceRoute: typeof LanddifferenceRoute
  PolicyLabRoute: typeof PolicyLabRoute
  RecordVsRealityRoute: typeof RecordVsRealityRoute
  ResearchHubRoute: typeof ResearchHubRoute
  WorkflowRoute: typeof WorkflowRoute
  InnovationImpactRoute: typeof InnovationImpactRoute
  InnovationPilotsRoute: typeof InnovationPilotsRoute
  InnovationSubmitRoute: typeof InnovationSubmitRoute
  InnovationIndexRoute: typeof InnovationIndexRoute
  InnovationChallengesChallengeIdRoute: typeof InnovationChallengesChallengeIdRoute
  InnovationWorkspaceProjectIdRoute: typeof InnovationWorkspaceProjectIdRoute
  InnovationChallengesIndexRoute: typeof InnovationChallengesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborativehub': {
      id: '/collaborativehub'
      path: '/collaborativehub'
      fullPath: '/collaborativehub'
      preLoaderRoute: typeof CollaborativehubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis-explorer': {
      id: '/gis-explorer'
      path: '/gis-explorer'
      fullPath: '/gis-explorer'
      preLoaderRoute: typeof GisExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis-explorer-3d': {
      id: '/gis-explorer-3d'
      path: '/gis-explorer-3d'
      fullPath: '/gis-explorer-3d'
      preLoaderRoute: typeof GisExplorer3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation-portal': {
      id: '/innovation-portal'
      path: '/innovation-portal'
      fullPath: '/innovation-portal'
      preLoaderRoute: typeof InnovationPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landdifference': {
      id: '/landdifference'
      path: '/landdifference'
      fullPath: '/landdifference'
      preLoaderRoute: typeof LanddifferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-lab': {
      id: '/policy-lab'
      path: '/policy-lab'
      fullPath: '/policy-lab'
      preLoaderRoute: typeof PolicyLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record-vs-reality': {
      id: '/record-vs-reality'
      path: '/record-vs-reality'
      fullPath: '/record-vs-reality'
      preLoaderRoute: typeof RecordVsRealityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-hub': {
      id: '/research-hub'
      path: '/research-hub'
      fullPath: '/research-hub'
      preLoaderRoute: typeof ResearchHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/': {
      id: '/innovation/'
      path: '/innovation'
      fullPath: '/innovation/'
      preLoaderRoute: typeof InnovationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/impact': {
      id: '/innovation/impact'
      path: '/innovation/impact'
      fullPath: '/innovation/impact'
      preLoaderRoute: typeof InnovationImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/pilots': {
      id: '/innovation/pilots'
      path: '/innovation/pilots'
      fullPath: '/innovation/pilots'
      preLoaderRoute: typeof InnovationPilotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/submit': {
      id: '/innovation/submit'
      path: '/innovation/submit'
      fullPath: '/innovation/submit'
      preLoaderRoute: typeof InnovationSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/challenges/': {
      id: '/innovation/challenges/'
      path: '/innovation/challenges'
      fullPath: '/innovation/challenges/'
      preLoaderRoute: typeof InnovationChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/challenges/$challengeId': {
      id: '/innovation/challenges/$challengeId'
      path: '/innovation/challenges/$challengeId'
      fullPath: '/innovation/challenges/$challengeId'
      preLoaderRoute: typeof InnovationChallengesChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation/workspace/$projectId': {
      id: '/innovation/workspace/$projectId'
      path: '/innovation/workspace/$projectId'
      fullPath: '/innovation/workspace/$projectId'
      preLoaderRoute: typeof InnovationWorkspaceProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollaborativehubRoute: CollaborativehubRoute,
  DashboardRoute: DashboardRoute,
  GisExplorerRoute: GisExplorerRoute,
  GisExplorer3dRoute: GisExplorer3dRoute,
  InnovationPortalRoute: InnovationPortalRoute,
  LanddifferenceRoute: LanddifferenceRoute,
  PolicyLabRoute: PolicyLabRoute,
  RecordVsRealityRoute: RecordVsRealityRoute,
  ResearchHubRoute: ResearchHubRoute,
  WorkflowRoute: WorkflowRoute,
  InnovationImpactRoute: InnovationImpactRoute,
  InnovationPilotsRoute: InnovationPilotsRoute,
  InnovationSubmitRoute: InnovationSubmitRoute,
  InnovationIndexRoute: InnovationIndexRoute,
  InnovationChallengesChallengeIdRoute: InnovationChallengesChallengeIdRoute,
  InnovationWorkspaceProjectIdRoute: InnovationWorkspaceProjectIdRoute,
  InnovationChallengesIndexRoute: InnovationChallengesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
